"""
core/retrieval/semantic.py
===========================
Vector similarity search retrieval.
Handles:
  - Semantic search (question -> embedding -> nearest vectors)
  - Filtered semantic search (with identifier or doc_type filter)

Uses pgvector cosine similarity via db_retrieval.py.
Embeddings generated by LM Studio via core/embedder.py -- unchanged.

All database access goes through db_retrieval.py.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from core.embedder import embed_texts
from core.retrieval.db_retrieval import search_vector, Point


# ---------------------------------------------------------------------------
# Semantic search
# Replaces: client.query_points(collection_name=X, query=vector, limit=N)
# ---------------------------------------------------------------------------
def semantic_search(
    collection_name: str,
    question: str,
    limit: int = 5,
) -> List[Point]:
    """
    Embed the question and find the most similar chunks by cosine similarity.
    Replaces Qdrant client.query_points().

    Returns Points sorted by similarity score (highest first).
    """
    vector = embed_texts([question.lower().strip()])[0]

    return search_vector(
        collection_name=collection_name,
        embedding=vector,
        limit=limit,
    )


def filtered_semantic_search(
    collection_name: str,
    question: str,
    identifier: str = None,
    doc_type: str = None,
    limit: int = 5,
) -> List[Point]:
    """
    Semantic search with optional filters.
    Replaces Qdrant filtered_search() with identifier filter.

    Useful for: finding chunks related to a specific tag/field
    while staying within semantic similarity bounds.
    """
    vector = embed_texts([question.lower().strip()])[0]

    return search_vector(
        collection_name=collection_name,
        embedding=vector,
        identifier=identifier,
        doc_type=doc_type,
        limit=limit,
    )


def embed_question(question: str) -> List[float]:
    """
    Embed a question and return the vector.
    Convenience wrapper around embed_texts for single questions.
    """
    return embed_texts([question.lower().strip()])[0]
